"""Extract cards/runes metadata from a local Isaac install.

Usage:
    python tools/build_cards.py [resources_dir]

Reads:
    pocketitems.xml   - card/rune definitions (id, type, name/description keys)
    stringtable.sta   - i18n strings (English names for V1)

Writes:
    tracker/data/cards.py   - {id: {name, sprite, removed, desc_es, group, unlock}}

Sprites (card_NNN.png) are generated by a separate task and are referenced
here only by filename. desc_es is left empty for V1 (Spanish translation is
a V2 follow-up).

The `unlock` field is the English unlock-condition text for cards gated by
an achievement (looked up via the `achievement=` attribute on <card>/<rune>
elements against tracker/data/achievements.json). Cards unlocked from the
start carry an empty string.
"""
from __future__ import annotations

import json
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

# Project root on sys.path so `from tracker.data...` works when invoked as
# `python tools/build_cards.py` from the repo root.
_PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

# EID Spanish card descriptions (generated by tools/build_eid.py). Optional —
# if the file isn't generated yet, all desc_es fields remain empty strings.
try:
    from tracker.data.eid_cards import EID_CARDS  # type: ignore
except ImportError:
    EID_CARDS: dict[int, dict] = {}

DEFAULT_RESOURCES = Path(
    "C:/Program Files (x86)/Steam/steamapps/common/"
    "The Binding of Isaac Rebirth/extracted_resources/resources"
)

# stringtable.sta: <key> has 8 <string> children, one per language, in this order
# (confirmed against pocketitems.xml's <languages> block — Key lang at index 0
# does not get its own <string> child, the first <string> is English).
_LANG_ORDER = ["en", "jp", "kr", "zh", "ru", "de", "es", "fr"]
_LANG_INDEX = {lang: i for i, lang in enumerate(_LANG_ORDER)}


def _strip_key(attr_value: str) -> str:
    """`#THE_FOOL_NAME` -> `THE_FOOL_NAME`."""
    return (attr_value or "").lstrip("#")


def parse_stringtable(stringtable_xml: Path) -> dict[str, dict[str, str]]:
    """Return {key_name: {lang_code: translated_string}}."""
    root = ET.parse(stringtable_xml).getroot()
    out: dict[str, dict[str, str]] = {}
    for key_elem in root.iter("key"):
        name = key_elem.get("name")
        if not name:
            continue
        strings = [s.text or "" for s in key_elem.findall("string")]
        translations: dict[str, str] = {}
        for lang, i in _LANG_INDEX.items():
            if i < len(strings) and strings[i]:
                translations[lang] = strings[i]
        out[name] = translations
    return out


def classify_group(elem_tag: str, type_attr: str, name_key: str) -> str:
    """Map a pocketitem element to one of the 5 logical groups.

    Rules (in priority order):
      1. name key starts with SOUL_OF_ -> 'objetos_alma'
         (the XML labels Soul stones type="rune", but they are conceptually
         a separate group in the tracker.)
      2. type contains 'reverse' (e.g. 'tarot_reverse') -> 'tarot_inverso'
      3. type == 'tarot' -> 'tarot_mayor'
      4. type == 'rune' OR elem tag == 'rune' -> 'runas'
      5. anything else (suit, special, object, ...) -> 'especiales'
    """
    t = (type_attr or "").lower()
    if name_key.startswith("SOUL_OF_"):
        return "objetos_alma"
    if "reverse" in t:
        return "tarot_inverso"
    if t == "tarot":
        return "tarot_mayor"
    if t == "rune" or elem_tag == "rune":
        return "runas"
    return "especiales"


def load_achievements_unlock(achievements_json: Path) -> dict[int, str]:
    """Return {achievement_id: unlock_text} parsed from achievements.json."""
    with achievements_json.open(encoding="utf-8") as fh:
        data = json.load(fh)
    out: dict[int, str] = {}
    for entry in data:
        try:
            aid = int(entry["Id"])
        except (KeyError, TypeError, ValueError):
            continue
        out[aid] = entry.get("Unlock") or ""
    return out


def parse_pocketitems(
    pocketitems_xml: Path,
    strings: dict[str, dict[str, str]],
    ach_unlock: dict[int, str],
) -> tuple[list[dict], list[str]]:
    """Return ([{id, name, removed, desc_es, group, unlock}, ...], warnings)."""
    root = ET.parse(pocketitems_xml).getroot()
    out: list[dict] = []
    warnings: list[str] = []

    # Track every distinct (tag, type) combination we saw, for the warning log.
    seen_type_combos: set[tuple[str, str]] = set()

    for elem in root:
        if elem.tag not in ("card", "rune"):
            # pilleffect (and any future tag) — not our concern here.
            continue
        id_attr = elem.get("id")
        if id_attr is None:
            continue
        try:
            card_id = int(id_attr)
        except ValueError:
            warnings.append(f"non-integer id={id_attr!r} — skipped")
            continue

        name_attr = elem.get("name") or ""
        # id=0 has name="NULL" — the canonical "no card" sentinel.
        if card_id == 0 or name_attr.upper() == "NULL":
            out.append({
                "id": card_id,
                "name": "",
                "removed": True,
                "desc_es": "",
                "group": "",
                "unlock": "",
            })
            continue

        name_key = _strip_key(name_attr)
        type_attr = elem.get("type") or ""
        seen_type_combos.add((elem.tag, type_attr.lower()))

        # English name from stringtable (V1 spec).
        name_en = strings.get(name_key, {}).get("en", "")
        if not name_en:
            warnings.append(
                f"id={card_id} key={name_key!r} has no English string — "
                f"using key as fallback"
            )
            # Last-resort fallback: humanize the key.
            base = name_key[:-5] if name_key.endswith("_NAME") else name_key
            name_en = " ".join(p.capitalize() for p in base.split("_"))

        group = classify_group(elem.tag, type_attr, name_key)
        # Spanish description from EID (if available — empty string otherwise).
        desc_es = EID_CARDS.get(card_id, {}).get("desc", "")
        # Unlock condition (English) — only present if the XML element has an
        # `achievement` attribute AND that id exists in achievements.json.
        ach_attr = elem.get("achievement")
        unlock = ""
        if ach_attr is not None:
            try:
                ach_id = int(ach_attr)
            except ValueError:
                warnings.append(
                    f"id={card_id} has non-integer achievement={ach_attr!r}"
                )
            else:
                if ach_id in ach_unlock:
                    unlock = ach_unlock[ach_id]
                else:
                    warnings.append(
                        f"id={card_id} references unknown achievement id "
                        f"{ach_id} — unlock left empty"
                    )
        out.append({
            "id": card_id,
            "name": name_en,
            "removed": False,
            "desc_es": desc_es,
            "group": group,
            "unlock": unlock,
        })

    # Warn (informational) about every type we saw, so future runs can
    # spot newly-introduced types we may need to map explicitly.
    known = {
        ("card", "tarot"), ("card", "suit"), ("card", "special"),
        ("card", "object"), ("card", "tarot_reverse"), ("card", "rune"),
        ("rune", "rune"),
    }
    for combo in sorted(seen_type_combos):
        if combo not in known:
            warnings.append(f"unknown (tag,type) combination: {combo}")

    out.sort(key=lambda d: d["id"])
    return out, warnings


def fill_id_gaps_as_removed(cards: list[dict]) -> list[dict]:
    """Mirror collectibles.py: if a numeric id is missing, insert a removed
    placeholder so consumers can iterate by id without holes."""
    by_id = {c["id"]: c for c in cards}
    if not by_id:
        return cards
    max_id = max(by_id)
    out = []
    for i in range(0, max_id + 1):
        if i in by_id:
            out.append(by_id[i])
        else:
            out.append({
                "id": i, "name": "", "removed": True,
                "desc_es": "", "group": "", "unlock": "",
            })
    return out


def write_cards_py(cards: list[dict], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        '"""Auto-generated by tools/build_cards.py — do not edit by hand."""',
        "from __future__ import annotations",
        "",
        "# id -> {name (English V1), sprite, removed, desc_es, group, unlock}",
        "# Sprite filenames live under tracker/assets/card_icons/ (generated separately).",
        '# Group ∈ {"tarot_mayor", "tarot_inverso", "runas", "especiales", "objetos_alma"}.',
        "# `unlock` is the English unlock-condition text (from achievements.json)",
        "# for cards gated by an achievement; empty string means unlocked by default.",
        "CARDS: dict[int, dict] = {",
    ]
    for c in cards:
        sprite = f"card_{c['id']:03d}.png" if not c["removed"] else ""
        lines.append(
            f"    {c['id']}: {{"
            f"'name': {c['name']!r}, "
            f"'sprite': {sprite!r}, "
            f"'removed': {c['removed']}, "
            f"'desc_es': {c['desc_es']!r}, "
            f"'group': {c['group']!r}, "
            f"'unlock': {c['unlock']!r}"
            f"}},"
        )
    lines.append("}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main(argv: list[str]) -> int:
    resources_dir = Path(argv[1]) if len(argv) > 1 else DEFAULT_RESOURCES
    if not resources_dir.is_dir():
        print(f"[build_cards] resources dir not found: {resources_dir}", file=sys.stderr)
        return 1

    pocketitems_path = resources_dir / "pocketitems.xml"
    stringtable_path = resources_dir / "stringtable.sta"
    for p in (pocketitems_path, stringtable_path):
        if not p.exists():
            print(f"[build_cards] missing input: {p}", file=sys.stderr)
            return 1

    print(f"[build_cards] resources: {resources_dir}")
    strings = parse_stringtable(stringtable_path)
    print(f"[build_cards] {len(strings)} stringtable keys")

    project_root = Path(__file__).resolve().parents[1]
    ach_path = project_root / "tracker" / "data" / "achievements.json"
    if ach_path.exists():
        ach_unlock = load_achievements_unlock(ach_path)
        print(f"[build_cards] {len(ach_unlock)} achievement unlock entries loaded")
    else:
        ach_unlock = {}
        print(f"[build_cards][warn] {ach_path} not found — unlock fields will be empty")

    cards_raw, warnings = parse_pocketitems(pocketitems_path, strings, ach_unlock)
    cards = fill_id_gaps_as_removed(cards_raw)

    for w in warnings:
        print(f"[build_cards][warn] {w}")

    out_py = project_root / "tracker" / "data" / "cards.py"
    write_cards_py(cards, out_py)

    real = sum(1 for c in cards if not c["removed"])
    with_desc = sum(1 for c in cards if not c["removed"] and c["desc_es"])
    with_unlock = sum(1 for c in cards if not c["removed"] and c["unlock"])
    print(f"[build_cards] wrote {len(cards)} cards ({real} real, "
          f"{len(cards) - real} removed/placeholder) -> {out_py}")
    print(f"[build_cards] EID Spanish descriptions: {with_desc}/{real} cards covered")
    print(f"[build_cards] Unlock conditions: {with_unlock}/{real} cards have one")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
