"""Extract pill metadata from a local Isaac install.

Usage:
    python tools/build_pills.py [resources_dir]

Reads:
    pocketitems.xml   - pilleffect definitions (id, name key)
    stringtable.sta   - i18n strings (English names for V1)

Writes:
    tracker/data/pills.py   - {id: {name, sprite, removed, desc_es, horse}}

Sprites (pill_NNN.png) are generated by a separate task and are referenced
here only by filename. desc_es is left empty for V1 (Spanish translation is
a V2 follow-up). horse is False for V1 (Horse pill distinction is V2).
"""
from __future__ import annotations

import sys
import xml.etree.ElementTree as ET
from pathlib import Path

# Project root on sys.path so `from tracker.data...` works when invoked as
# `python tools/build_pills.py` from the repo root.
_PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

# EID Spanish pill descriptions (generated by tools/build_eid.py). Optional —
# if the file isn't generated yet, all desc_es fields remain empty strings.
try:
    from tracker.data.eid_pills import EID_PILLS  # type: ignore
except ImportError:
    EID_PILLS: dict[int, dict] = {}

DEFAULT_RESOURCES = Path(
    "C:/Program Files (x86)/Steam/steamapps/common/"
    "The Binding of Isaac Rebirth/extracted_resources/resources"
)

# stringtable.sta: <key> has 8 <string> children, one per language, in this order
# (confirmed against pocketitems.xml's <languages> block — Key lang at index 0
# does not get its own <string> child, the first <string> is English).
_LANG_ORDER = ["en", "jp", "kr", "zh", "ru", "de", "es", "fr"]
_LANG_INDEX = {lang: i for i, lang in enumerate(_LANG_ORDER)}


def _strip_key(attr_value: str) -> str:
    """`#BAD_GAS_NAME` -> `BAD_GAS_NAME`."""
    return (attr_value or "").lstrip("#")


def parse_stringtable(stringtable_xml: Path) -> dict[str, dict[str, str]]:
    """Return {key_name: {lang_code: translated_string}}."""
    root = ET.parse(stringtable_xml).getroot()
    out: dict[str, dict[str, str]] = {}
    for key_elem in root.iter("key"):
        name = key_elem.get("name")
        if not name:
            continue
        strings = [s.text or "" for s in key_elem.findall("string")]
        translations: dict[str, str] = {}
        for lang, i in _LANG_INDEX.items():
            if i < len(strings) and strings[i]:
                translations[lang] = strings[i]
        out[name] = translations
    return out


def parse_pilleffects(
    pocketitems_xml: Path, strings: dict[str, dict[str, str]]
) -> tuple[list[dict], list[str]]:
    """Return ([{id, name, removed, desc_es, horse}, ...], warnings)."""
    root = ET.parse(pocketitems_xml).getroot()
    out: list[dict] = []
    warnings: list[str] = []

    for elem in root:
        if elem.tag != "pilleffect":
            continue
        id_attr = elem.get("id")
        if id_attr is None:
            continue
        try:
            pill_id = int(id_attr)
        except ValueError:
            warnings.append(f"non-integer id={id_attr!r} — skipped")
            continue

        name_attr = elem.get("name") or ""
        if not name_attr:
            warnings.append(f"id={pill_id} has no name attribute — skipped")
            continue

        name_key = _strip_key(name_attr)
        # English name from stringtable (V1 spec).
        name_en = strings.get(name_key, {}).get("en", "")
        if not name_en:
            warnings.append(
                f"id={pill_id} key={name_key!r} has no English string — "
                f"using key as fallback"
            )
            base = name_key[:-5] if name_key.endswith("_NAME") else name_key
            name_en = " ".join(p.capitalize() for p in base.split("_"))

        # Spanish description from EID (if available — empty string otherwise).
        desc_es = EID_PILLS.get(pill_id, {}).get("desc", "")
        out.append({
            "id": pill_id,
            "name": name_en,
            "removed": False,
            "desc_es": desc_es,
            "horse": False,  # V1: Horse pill distinction deferred.
        })

    out.sort(key=lambda d: d["id"])
    return out, warnings


def fill_id_gaps_as_removed(pills: list[dict]) -> list[dict]:
    """If a numeric id is missing, insert a removed placeholder so consumers
    can iterate by id without holes."""
    by_id = {p["id"]: p for p in pills}
    if not by_id:
        return pills
    max_id = max(by_id)
    out = []
    for i in range(0, max_id + 1):
        if i in by_id:
            out.append(by_id[i])
        else:
            out.append({
                "id": i, "name": "", "removed": True,
                "desc_es": "", "horse": False,
            })
    return out


def write_pills_py(pills: list[dict], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        '"""Auto-generated by tools/build_pills.py — do not edit by hand."""',
        "from __future__ import annotations",
        "",
        "# id -> {name (English V1), sprite, removed, desc_es, horse}",
        "# Sprite filenames live under tracker/assets/pill_icons/ (generated separately).",
        "# horse=False for all V1 entries (Horse pill distinction deferred to V2).",
        "PILLS: dict[int, dict] = {",
    ]
    for p in pills:
        sprite = f"pill_{p['id']:03d}.png" if not p["removed"] else ""
        lines.append(
            f"    {p['id']}: {{"
            f"'name': {p['name']!r}, "
            f"'sprite': {sprite!r}, "
            f"'removed': {p['removed']}, "
            f"'desc_es': {p['desc_es']!r}, "
            f"'horse': {p['horse']}"
            f"}},"
        )
    lines.append("}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main(argv: list[str]) -> int:
    resources_dir = Path(argv[1]) if len(argv) > 1 else DEFAULT_RESOURCES
    if not resources_dir.is_dir():
        print(f"[build_pills] resources dir not found: {resources_dir}", file=sys.stderr)
        return 1

    pocketitems_path = resources_dir / "pocketitems.xml"
    stringtable_path = resources_dir / "stringtable.sta"
    for p in (pocketitems_path, stringtable_path):
        if not p.exists():
            print(f"[build_pills] missing input: {p}", file=sys.stderr)
            return 1

    print(f"[build_pills] resources: {resources_dir}")
    strings = parse_stringtable(stringtable_path)
    print(f"[build_pills] {len(strings)} stringtable keys")

    pills_raw, warnings = parse_pilleffects(pocketitems_path, strings)
    pills = fill_id_gaps_as_removed(pills_raw)

    for w in warnings:
        print(f"[build_pills][warn] {w}")

    project_root = Path(__file__).resolve().parents[1]
    out_py = project_root / "tracker" / "data" / "pills.py"
    write_pills_py(pills, out_py)

    real = sum(1 for p in pills if not p["removed"])
    with_desc = sum(1 for p in pills if not p["removed"] and p["desc_es"])
    print(f"[build_pills] wrote {len(pills)} pills ({real} real, "
          f"{len(pills) - real} removed/placeholder) -> {out_py}")
    print(f"[build_pills] EID Spanish descriptions: {with_desc}/{real} pills covered")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
