"""Genera tracker/assets/trinkets_inline.js con TODOS los trinkets de
Repentance/Repentance+ (188 reales, id 1..189 con el 47 vacío).

Sustituye al antiguo `extract_trinkets.py` (que solo extraía los unlockables).

Estructura de salida:
    window.TRINKETS_DATA = [
      {"id":1,"name":"Swallowed Penny","achId":101,"unlock":"...","desc":"..."},
      {"id":2,"name":"Petrified Poop","achId":null,"unlock":"Inicial - disponible desde el principio","desc":"..."},
      ...
    ];

- `id` es el trinket id canónico del juego (1..189).
- `achId` es null si el trinket viene desbloqueado desde el inicio.
- `unlock` es la condición de desbloqueo (texto en español).
- `desc` es el efecto en español, una o dos líneas.

El icono se renderiza en challenges.html como `trinket_icons/{id}.png`.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Lista canónica de 188 trinkets (id 47 vacío en Repentance).
# Cada tupla: (id, name, achId|None, unlock, desc)
# - Los unlocks/descs existentes se mantienen del trinkets_inline.js anterior
#   cuando aplican.
# - Para los trinkets "iniciales" (achId=None), unlock="Inicial - disponible
#   desde el principio" y desc redactada de cero a partir del conocimiento
#   del juego.
TRINKETS: list[tuple[int, str, int | None, str, str]] = [
    (1, "Swallowed Penny", 101, "Completa Slow Roll (reto #15)",
     "Al recibir daño sueltas 1 moneda."),
    (2, "Petrified Poop", None, "Inicial - disponible desde el principio",
     "↑ Suerte +1 para que las cacas suelten mejores premios al destruirlas."),
    (3, "AAA Battery", None, "Inicial - disponible desde el principio",
     "Si tu objeto activo está a 1 carga de poder usarse, se carga del todo."),
    (4, "Broken Remote", None, "Inicial - disponible desde el principio",
     "Tu objeto activo teletransporta a Isaac a una sala aleatoria al usarse."),
    (5, "Purple Heart", None, "Inicial - disponible desde el principio",
     "Los corazones malignos (negros, eternos, etc.) aparecen el doble de veces."),
    (6, "Broken Magnet", None, "Inicial - disponible desde el principio",
     "Atrae bombas y baterías hacia Isaac."),
    (7, "Rosary Bead", None, "Inicial - disponible desde el principio",
     "Las salas pueden contener una Bible al limpiarlas."),
    (8, "Cartridge", None, "Inicial - disponible desde el principio",
     "Convierte la sala en un minijuego 8-bit estilo Game Boy al entrar."),
    (9, "Pulse Worm", None, "Inicial - disponible desde el principio",
     "Tus lágrimas se mueven en ondas senoidales (zigzag)."),
    (10, "Wiggle Worm", None, "Inicial - disponible desde el principio",
     "Tus lágrimas se mueven en zigzag (movimiento serpenteante)."),
    (11, "Ring Worm", None, "Inicial - disponible desde el principio",
     "Tus lágrimas se mueven en espiral."),
    (12, "Flat Worm", None, "Inicial - disponible desde el principio",
     "↑ Daño +1.2 y ↓ Alcance −1 (lágrimas anchas y planas)."),
    (13, "Store Credit", 118, "Derrota a ??? con Lazarus",
     "La próxima vez que entres a una tienda, un item de la tienda es gratis."),
    (14, "Callus", None, "Inicial - disponible desde el principio",
     "No te hace daño caer en agujeros ni en pinchos del suelo."),
    (15, "Lucky Rock", 85, "Destruye 100 rocas",
     "Las rocas pueden soltar monedas al destruirse."),
    (16, "Mom's Toenail", None, "Inicial - disponible desde el principio",
     "Una vez por sala, el pie de mamá aplasta un enemigo aleatorio."),
    (17, "Black Lipstick", 111, "Derrota a The Lamb con Eve",
     "Los corazones negros aparecen más a menudo."),
    (18, "Bible Tract", None, "Inicial - disponible desde el principio",
     "Las salas pueden contener un Soul Heart al limpiarlas."),
    (19, "Paper Clip", None, "Inicial - disponible desde el principio",
     "Abre cofres dorados sin necesidad de llave."),
    (20, "Monkey's Paw", None, "Inicial - disponible desde el principio",
     "Cada vez que llegas a medio corazón recibes un Black Heart (máx. 3 veces por run)."),
    (21, "Mysterious Paper", 123, "Pasa ??? con Eden",
     "Cada piso te aplica al azar A Missing Page, A Polaroid, A Negative o Missing Poster."),
    (22, "Daemon's Tail", 127, "Derrota a Satan con Azazel",
     "Los corazones rojos que aparezcan son corazones negros."),
    (23, "Missing Poster", 149, "Derrota a The Lamb con Isaac",
     "Si mueres en una Sacrifice Room llevándolo, renaces como The Lost (y lo desbloqueas)."),
    (24, "Butt Penny", None, "Inicial - disponible desde el principio",
     "Al recibir daño tiras un montón de monedas al suelo."),
    (25, "Mysterious Candy", None, "Inicial - disponible desde el principio",
     "Cada 10 segundos al azar: pedo, caca, lágrima extra o llanto."),
    (26, "Hook Worm", None, "Inicial - disponible desde el principio",
     "Tus lágrimas viajan en zigzag rectangular."),
    (27, "Whip Worm", None, "Inicial - disponible desde el principio",
     "↑ Velocidad de lágrimas +0.75."),
    (28, "Broken Ankh", 117, "Derrota a Satan con Lazarus",
     "33% de probabilidad de revivir como ??? al morir."),
    (29, "Fish Head", None, "Inicial - disponible desde el principio",
     "Una mosca azul te orbita y te defiende. Sueltas más moscas al recibir daño."),
    (30, "Pinky Eye", None, "Inicial - disponible desde el principio",
     "Tus lágrimas envenenan a los enemigos al azar."),
    (31, "Push Pin", None, "Inicial - disponible desde el principio",
     "Tus lágrimas atraviesan enemigos (piercing) al azar."),
    (32, "Liberty Cap", None, "Inicial - disponible desde el principio",
     "Cada piso recibes al azar un efecto temporal de seta (Magic Mushroom, Mini Mush, etc.)."),
    (33, "Umbilical Cord", None, "Inicial - disponible desde el principio",
     "Al bajar a medio corazón, spawnea Little Steven como familiar."),
    (34, "Child's Heart", None, "Inicial - disponible desde el principio",
     "Los corazones aparecen más a menudo en las salas."),
    (35, "Curved Horn", 52, "Derrota a The Lamb con Judas",
     "↑ Daño +1."),
    (36, "Rusted Key", None, "Inicial - disponible desde el principio",
     "Las salas pueden contener una Key al limpiarlas."),
    (37, "Goat Hoof", None, "Inicial - disponible desde el principio",
     "↑ Velocidad +0.15."),
    (38, "Mom's Pearl", None, "Inicial - disponible desde el principio",
     "Los corazones de alma (soul hearts) aparecen el doble de veces."),
    (39, "Cancer", None, "Inicial - disponible desde el principio",
     "↑ Cadencia de disparo +0.7 (tear delay −1)."),
    (40, "Red Patch", None, "Inicial - disponible desde el principio",
     "Al recibir daño, 30% de probabilidad de subir el daño esa run (+0.5)."),
    (41, "Match Stick", None, "Inicial - disponible desde el principio",
     "Las salas pueden contener una Bomb al limpiarlas."),
    (42, "Lucky Toe", 61, "Vuela a 20 Shopkeepers",
     "↑ Suerte +1."),
    (43, "Cursed Skull", None, "Inicial - disponible desde el principio",
     "Al llegar a medio corazón, te teletransportas a una sala aleatoria."),
    (44, "Safety Cap", None, "Inicial - disponible desde el principio",
     "Las salas pueden contener una Pill al limpiarlas."),
    (45, "Ace of Spades", None, "Inicial - disponible desde el principio",
     "Las salas pueden contener una Card al limpiarlas."),
    (46, "Isaac's Fork", None, "Inicial - disponible desde el principio",
     "Las salas pueden contener un corazón rojo extra."),
    # 47 vacío en Repentance.
    (48, "A Missing Page", None, "Inicial - disponible desde el principio",
     "20% de probabilidad de hacer daño a todos los enemigos de la sala (40 dmg) al recibir golpe."),
    (49, "Bloody Penny", 55, "Derrota a ??? con Samson",
     "Las salas pueden contener un Half Red Heart al limpiarlas."),
    (50, "Burnt Penny", 60, "Completa Beans! (reto #13)",
     "Las salas pueden contener una Coin al limpiarlas."),
    (51, "Flat Penny", None, "Inicial - disponible desde el principio",
     "Al recogerla, atraes monedas hacia ti durante un rato."),
    (52, "Counterfeit Penny", None, "Inicial - disponible desde el principio",
     "Al recoger monedas, hay probabilidad de soltar una segunda moneda falsa."),
    (53, "Tick", None, "Inicial - disponible desde el principio",
     "A los jefes les quitas 15% de su vida al entrar a la sala. ¡No se puede soltar!"),
    (54, "Isaac's Head", 70, "Completa Boss Rush con Isaac",
     "Familiar: la cabeza de Isaac que dispara lágrimas durante 4s, luego se recarga."),
    (55, "Maggy's Faith", 71, "Derrota a The Lamb con Magdalene",
     "↑ Suerte +1."),
    (56, "Judas' Tongue", 72, "Derrota a Satan con Judas",
     "Los items del Devil Room cuestan la mitad de corazones."),
    (57, "???'s Soul", 73, "Derrota a The Lamb con ???",
     "Familiar volador que da vueltas alrededor de Isaac e inflige daño por contacto."),
    (58, "Samson's Lock", 74, "Derrota a The Lamb con Samson",
     "Al limpiar una sala, 12% de probabilidad de subir el daño esa run (+0.5)."),
    (59, "Cain's Eye", 75, "Derrota a ??? con Cain",
     "Al entrar a un piso, 25% de probabilidad de aplicar Compass todo el piso."),
    (60, "Eve's Bird Foot", 76, "Derrota a Isaac con Eve",
     "Spawnea Dead Birds al limpiar salas (al azar)."),
    (61, "The Left Hand", 77, "Derrota a Ultra Pride con cualquier personaje, o a ??? con Judas",
     "Los Golden Chests se convierten en Red Chests (cofres del diablo)."),
    (62, "Shiny Rock", None, "Inicial - disponible desde el principio",
     "Las rocas pueden soltar Tinted Rocks (rocas que sueltan items) al destruirse."),
    (63, "Safety Scissors", None, "Inicial - disponible desde el principio",
     "Convierte las bombas con mecha corta en bombas normales (extiende el tiempo)."),
    (64, "Rainbow Worm", None, "Inicial - disponible desde el principio",
     "Aplica un efecto worm aleatorio cada sala (Pulse, Wiggle, Ring, Flat, etc.)."),
    (65, "Tape Worm", None, "Inicial - disponible desde el principio",
     "↑ Alcance +0.75 (las lágrimas vuelan más lejos)."),
    (66, "Lazy Worm", None, "Inicial - disponible desde el principio",
     "↓ Velocidad de lágrimas (viajan más lento y caen al suelo más rápido)."),
    (67, "Cracked Dice", 196, "Derrota a Ultra Greed con ???",
     "Al recibir daño, te aplica un efecto aleatorio de D6, D8, D10 o D20."),
    (68, "Super Magnet", None, "Inicial - disponible desde el principio",
     "Atrae cualquier pickup (monedas, llaves, bombas, corazones, baterías) hacia Isaac."),
    (69, "Faded Polaroid", None, "Inicial - disponible desde el principio",
     "Te vuelve invisible a la mayoría de enemigos hasta que disparas."),
    (70, "Louse", None, "Inicial - disponible desde el principio",
     "Tus lágrimas tienen 25% de probabilidad de aplicar sangrado (slow + bleed)."),
    (71, "Bob's Bladder", None, "Inicial - disponible desde el principio",
     "Tus lágrimas dejan creep verde (charcos de veneno) al impactar."),
    (72, "Watch Battery", None, "Inicial - disponible desde el principio",
     "Cada sala, 10% de probabilidad de soltar una Lil' Battery."),
    (73, "Blasting Cap", None, "Inicial - disponible desde el principio",
     "Las bombas pueden duplicarse al recogerlas (15% de probabilidad)."),
    (74, "Stud Finder", 230, "Completa BRAINS! (reto #27)",
     "Las salas pueden contener un nickel (5¢) al limpiarlas."),
    (75, "Error", None, "Inicial - disponible desde el principio",
     "Te aplica un efecto positivo (o negativo) aleatorio al usar tu objeto activo."),
    (76, "Poker Chip", 229, "Completa I RULE! (reto #26)",
     "El primer pedestal de cada piso suelta un segundo item al recogerlo."),
    (77, "Blister", None, "Inicial - disponible desde el principio",
     "↑ Daño +2 cuando llevas un objeto activo a 0 cargas."),
    (78, "Second Hand", None, "Inicial - disponible desde el principio",
     "Duplica la duración de los efectos de estatus (envenenado, congelado, etc.) que aplicas."),
    (79, "Endless Nameless", None, "Inicial - disponible desde el principio",
     "Cuando usas una pill, card o rune, hay probabilidad de duplicarla."),
    (80, "Black Feather", 197, "Derrota a Ultra Greed con Eve",
     "↑ Daño +0.16 por cada item maligno (Devil/Dark) que tengas."),
    (81, "Blind Rage", None, "Inicial - disponible desde el principio",
     "Te vuelve invulnerable durante el primer segundo al entrar a cualquier sala."),
    (82, "Golden Horse Shoe", None, "Inicial - disponible desde el principio",
     "Las máquinas tragaperras y máquinas de mendigos te dan más recompensas."),
    (83, "Store Key", None, "Inicial - disponible desde el principio",
     "Abre cualquier puerta de tienda y mantiene la puerta abierta tras pagar."),
    (84, "Rib of Greed", 204, "Derrota a Ultra Greed con Keeper",
     "Al recoger una moneda, 25% de probabilidad de soltar un Black Heart."),
    (85, "Karma", 239, "Derrota a The Lamb con Keeper",
     "Donar a la Greed Donation Machine te da items extra."),
    (86, "Lil Larva", None, "Inicial - disponible desde el principio",
     "Tras matar enemigos, hay probabilidad de spawnear Blue Flies amigas."),
    (87, "Mom's Locket", None, "Inicial - disponible desde el principio",
     "Recoger corazones rojos cura un poco más (+1/2 corazón extra)."),
    (88, "NO!", None, "Inicial - disponible desde el principio",
     "Bloquea un tipo de pill/card aleatoria por piso (no aparecerán)."),
    (89, "Child Leash", None, "Inicial - disponible desde el principio",
     "Tus familiares se mantienen pegados a Isaac y no se quedan rezagados."),
    (90, "Brown Cap", None, "Inicial - disponible desde el principio",
     "↑ Cadencia de disparo y daño cuando estás con caca al lado (efecto de hongo)."),
    (91, "Meconium", 300, "Derrota a Ultra Greedier con ???",
     "10% de probabilidad de Black Heart al matar enemigos."),
    (92, "Cracked Crown", None, "Inicial - disponible desde el principio",
     "↑ Multiplicador a stats: amplifica daño, cadencia y otras stats."),
    (93, "Used Diaper", None, "Inicial - disponible desde el principio",
     "Las salas pueden contener una bomba o una llave al limpiarlas."),
    (94, "Fish Tail", None, "Inicial - disponible desde el principio",
     "Duplica los disparos de tus familiares (efecto similar a Forever Alone)."),
    (95, "Black Tooth", None, "Inicial - disponible desde el principio",
     "Cada sala, hay probabilidad de soltar lágrimas como Mom's Wig (arañas)."),
    (96, "Ouroboros Worm", None, "Inicial - disponible desde el principio",
     "Tus lágrimas viajan en espiral cerrada en lazo."),
    (97, "Tonsil", None, "Inicial - disponible desde el principio",
     "Al recibir daño, hay probabilidad de spawnear un familiar Tonsil que dispara."),
    (98, "Nose Goblin", None, "Inicial - disponible desde el principio",
     "Cada pocas lágrimas, lanzas un moco grande que hace daño extra."),
    (99, "Super Ball", None, "Inicial - disponible desde el principio",
     "Te concede un efecto pasivo aleatorio (cambia cada piso)."),
    (100, "Vibrant Bulb", None, "Inicial - disponible desde el principio",
     "Si llevas el active a carga completa, ↑ Daño +1.5."),
    (101, "Dim Bulb", None, "Inicial - disponible desde el principio",
     "Si llevas el active a 0 cargas, ↑ Cadencia y daño."),
    (102, "Fragmented Card", None, "Inicial - disponible desde el principio",
     "Permite llevar 1 card extra (slot adicional para cartas)."),
    (103, "Equality!", None, "Inicial - disponible desde el principio",
     "Tus pickups de monedas/llaves/bombas se redondean al alza (10/5 in lugar de 9/4)."),
    (104, "Wish Bone", None, "Inicial - disponible desde el principio",
     "Las máquinas tragaperras pueden soltar un item de pedestal después de varios usos."),
    (105, "Bag Lunch", None, "Inicial - disponible desde el principio",
     "Te da una ración de comida (efecto Lunch) que se consume al usarla."),
    (106, "Lost Cork", None, "Inicial - disponible desde el principio",
     "Las píldoras tienen efectos amplificados (positivos y negativos)."),
    (107, "Crow Heart", 302, "Derrota a Ultra Greedier con Eve",
     "Los corazones rojos que recoges se convierten en Black Hearts."),
    (108, "Walnut", None, "Inicial - disponible desde el principio",
     "Si te haces daño 5 veces con él, se rompe y suelta un objeto pasivo."),
    (109, "Duct Tape", None, "Inicial - disponible desde el principio",
     "Tus familiares se mantienen pegados a tu posición (no se mueven solos)."),
    (110, "Silver Dollar", 284, "Derrota a Delirium con Cain",
     "Hace que aparezca una tienda en Womb/Corpse. Debes tenerlo al entrar al piso."),
    (111, "Bloody Crown", 287, "Derrota a Delirium con Samson",
     "Cada piso, una sala normal extra se convierte en sala de jefe."),
    (112, "Pay to Win", None, "Inicial - disponible desde el principio",
     "Cada piso, hay un item en venta en una tienda especial accesible por moneda."),
    (113, "Locust of War", 310, "Derrota a Isaac con Apollyon",
     "Al entrar a sala con enemigos, spawnea una langosta roja que explota."),
    (114, "Locust of Pestilence", 311, "Derrota a Satan con Apollyon",
     "Al entrar a sala con enemigos, spawnea una langosta verde que envenena."),
    (115, "Locust of Famine", 312, "Derrota a ??? con Apollyon",
     "Al entrar a sala con enemigos, spawnea una langosta amarilla que ralentiza."),
    (116, "Locust of Death", 313, "Derrota a The Lamb con Apollyon",
     "Al entrar a sala con enemigos, spawnea una langosta negra que inflige mucho daño."),
    (117, "Locust of Conquest", 314, "Completa Boss Rush con Apollyon",
     "Al entrar a sala con enemigos, spawnea 1–4 langostas blancas con 2× tu daño."),
    (118, "Bat Wing", 304, "Derrota a Ultra Greedier con Azazel",
     "Cada vez que matas a un enemigo, 10% de probabilidad de un Black Heart."),
    (119, "Stem Cell", 301, "Derrota a Ultra Greedier con Samson",
     "Cada sala, cura 1/2 corazón si te falta vida."),
    (120, "Hairpin", 358, "Recarga usando Lil' Batteries 20 veces",
     "Recargas tu activo +1 al recoger una batería (Lil' Battery)."),
    (121, "Wooden Cross", 359, "Duerme en una cama",
     "+1 contenedor de corazón al inicio de cada capítulo."),
    (122, "Butter!", 360, "Completa 2 Victory Laps y empieza una 3.ª",
     "Tus trinkets se caen con frecuencia al recibir daño (combina con varios trinkets)."),
    (123, "Filigree Feather", 370, "Consigue las dos Key Pieces",
     "Las Angel Statues sueltan más items."),
    (124, "Door Stop", 375, "Vuela puertas y paredes de Secret Room 50 veces",
     "Las puertas voladas o destruidas no se cierran tras pasar (no se regenera la pared)."),
    (125, "Extension Cord", 381, "Ten The Battery, 9 Volt y Car Battery en tu colección",
     "Si tienes The Battery, 9 Volt y Car Battery, tu activo se sobrecarga (++cargas)."),
    (126, "Rotten Penny", 388, "Ten 20 Blue Flies a la vez",
     "Al recoger una moneda, 25% de probabilidad de spawnear una Blue Fly amiga."),
    (127, "Baby-Bender", 389, "Usa I - The Magician o Telepathy for Dummies teniendo lágrimas homing",
     "Si usas I-The Magician o Telepathy mientras tienes homing, los enemigos se vuelven amigos un rato."),
    (128, "Finger Bone", 399, "Derrota a Ultra Greed con The Forgotten",
     "Al matar enemigos hay probabilidad de spawnear un Bone Heart."),
    (129, "Jawbreaker", None, "Inicial - disponible desde el principio",
     "Tus lágrimas tienen probabilidad de aturdir (knockback) a enemigos."),
    (130, "Chewed Pen", None, "Inicial - disponible desde el principio",
     "Tus lágrimas vuelan al doble de velocidad pero hacen menos daño."),
    (131, "Blessed Penny", 419, "Derrota a ??? con Bethany",
     "Las salas pueden contener un Soul Heart o Half Soul Heart al limpiarlas."),
    (132, "Broken Syringe", None, "Inicial - disponible desde el principio",
     "Aplica un efecto de pill aleatorio al inicio de cada sala."),
    (133, "Short Fuse", None, "Inicial - disponible desde el principio",
     "Tus bombas tienen mecha más corta (explotan más rápido)."),
    (134, "Gigante Bean", None, "Inicial - disponible desde el principio",
     "Al usar Bean items, los efectos son más potentes."),
    (135, "A Lighter", None, "Inicial - disponible desde el principio",
     "Tus lágrimas pueden quemar a los enemigos (efecto fuego, daño con el tiempo)."),
    (136, "Broken Padlock", None, "Inicial - disponible desde el principio",
     "Las puertas con candado tienen probabilidad de abrirse sin llave."),
    (137, "Myosotis", None, "Inicial - disponible desde el principio",
     "Al cambiar de piso, los pickups que te dejaste atrás aparecen en la primera sala del siguiente."),
    (138, "'M", 458, "Derrota a Mother con Eden",
     "Al usar tu objeto activo, ejecuta un efecto aleatorio (como D Infinity)."),
    (139, "Teardrop Charm", None, "Inicial - disponible desde el principio",
     "↑ Cadencia de disparo (tear delay reducido) en la primera sala de cada piso."),
    (140, "Apple of Sodom", None, "Inicial - disponible desde el principio",
     "Al recibir daño, suelta una manzana que cura medio corazón si la recoges."),
    (141, "Forgotten Lullaby", 408, "Vuela el cráneo de The Siren tras derrotarla",
     "Convierte tu objeto activo en disparable en cada sala sin necesidad de recargarlo manualmente."),
    (142, "Beth's Faith", 421, "Completa Boss Rush con Bethany",
     "Las Wisps blancas tienen tu daño multiplicado."),
    (143, "Old Capacitor", 545, "Mata a 10 Battery Bums",
     "Convierte el daño que recibes en cargas para tu activo."),
    (144, "Brain Worm", None, "Inicial - disponible desde el principio",
     "Tus lágrimas tienen homing fuerte (siguen a los enemigos)."),
    (145, "Perfection", None, "Inicial - disponible desde el principio",
     "↑ Suerte +10. Se cae automáticamente al recibir cualquier daño."),
    (146, "Devil's Crown", 454, "Derrota a Mother con Azazel",
     "Convierte los items del Treasure Room en items del Devil Room a precio de monedas."),
    (147, "Charged Penny", 523, "Dona a varios Battery Bums hasta que suelten un item",
     "Tu activo se carga al recoger monedas."),
    (148, "Friendship Necklace", None, "Inicial - disponible desde el principio",
     "Tus familiares se reorganizan en una formación más útil alrededor de Isaac."),
    (149, "Panic Button", None, "Inicial - disponible desde el principio",
     "Al recibir daño que te baja a medio corazón o menos, activa tu objeto activo gratis."),
    (150, "Blue Key", None, "Inicial - disponible desde el principio",
     "Cada piso, hay probabilidad de spawnear una Blue Door extra con sala de recompensa."),
    (151, "Flat File", None, "Inicial - disponible desde el principio",
     "Las llaves no se rompen al usarlas en cofres (probabilidad de no consumirse)."),
    (152, "Telescope Lens", None, "Inicial - disponible desde el principio",
     "Cada piso, revela la posición del piso superior en el mapa."),
    (153, "Mom's Lock", 548, "Derrota a Isaac, ???, Satan y The Lamb con Tainted Isaac",
     "Las llaves se duplican al recogerlas a veces."),
    (154, "Dice Bag", 549, "Derrota a Mother con Tainted Isaac",
     "Cada sala, hay probabilidad de spawnear un dado aleatorio (D6, D20, etc.) en el suelo."),
    (155, "Holy Crown", 550, "Derrota a Isaac, ???, Satan y The Lamb con Tainted Magdalene",
     "Las Angel Rooms están garantizadas en cada piso si no entras a Devil."),
    (156, "Mother's Kiss", 551, "Derrota a Mother con Tainted Magdalene",
     "↑ +1 contenedor de corazón al inicio de cada capítulo."),
    (157, "Torn Card", 565, "Derrota a Mother con Tainted Lazarus",
     "Cada 15 enemigos matados, una card aleatoria spawnea en el suelo."),
    (158, "Torn Pocket", 564, "Derrota a Isaac, ???, Satan y The Lamb con Tainted Lazarus",
     "Sueltas 1 moneda cada vez que recibes daño."),
    (159, "Gilded Key", 552, "Derrota a Isaac, ???, Satan y The Lamb con Tainted Cain",
     "Cofres dorados sueltan items extra."),
    (160, "Lucky Sack", 553, "Derrota a Mother con Tainted Cain",
     "Las bolsas (Grab Bags) sueltan el doble de pickups."),
    (161, "Wicked Crown", 562, "Derrota a Isaac, ???, Satan y The Lamb con Tainted Azazel",
     "Los jefes sueltan más drops (corazones, monedas, etc.)."),
    (162, "Azazel's Stump", 563, "Derrota a Mother con Tainted Azazel",
     "Lanza brimstone corto en cada sala (auto-aimed)."),
    (163, "Dingle Berry", 556, "Derrota a Isaac, ???, Satan y The Lamb con Tainted ???",
     "Cada piso, 50% de probabilidad de spawnear un Dip familiar."),
    (164, "Ring Cap", 557, "Derrota a Mother con Tainted ???",
     "Las bombas hacen +1 de daño extra y suenan más fuerte."),
    (165, "Nuh Uh!", 566, "Derrota a Isaac, ???, Satan y The Lamb con Tainted Eden",
     "Al recibir daño, 50% de probabilidad de no perder vida."),
    (166, "Modeling Clay", 567, "Derrota a Mother con Tainted Eden",
     "Te concede el efecto de un item pasivo aleatorio durante el piso."),
    (167, "Polished Bone", 576, "Derrota a Isaac, ???, Satan y The Lamb con Tainted Forgotten",
     "Cada sala spawnea un Bony familiar aliado."),
    (168, "Hollow Heart", 577, "Derrota a Mother con Tainted Forgotten",
     "↑ +1 Bone Heart al inicio de cada capítulo."),
    (169, "Kid's Drawing", 568, "Derrota a Isaac, ???, Satan y The Lamb con Tainted Lost",
     "Spawnea un familiar 'Imaginary Friend' que ataca enemigos."),
    (170, "Crystal Key", None, "Inicial - disponible desde el principio",
     "Cada piso, hay probabilidad de spawnear una Crystal Door (sala especial)."),
    (171, "Keeper's Bargain", 572, "Derrota a Isaac, ???, Satan y The Lamb con Tainted Keeper",
     "Devil Deals cuestan 1 moneda en lugar de corazones (sólo para Keeper)."),
    (172, "Cursed Penny", 573, "Derrota a Mother con Tainted Keeper",
     "Al recoger una moneda, te teletransportas a una sala aleatoria."),
    (173, "Your Soul", 554, "Derrota a Isaac, ???, Satan y The Lamb con Tainted Judas",
     "Al morir, te da una segunda vida (revives como The Lost una vez)."),
    (174, "Number Magnet", 555, "Derrota a Mother con Tainted Judas",
     "Atrae las monedas hacia Isaac (rango grande)."),
    (175, "Strange Key", 558, "Derrota a Isaac, ???, Satan y The Lamb con Tainted Eve",
     "Abre cofres con llaves coloreadas sin gastar la llave."),
    (176, "Lil Clot", 559, "Derrota a Mother con Tainted Eve",
     "Cada vez que recibes daño, suelta sangre que cura medio corazón si la recoges."),
    (177, "Temporary Tattoo", 560, "Derrota a Isaac, ???, Satan y The Lamb con Tainted Samson",
     "+0.5 daño durante la primera sala de cada piso."),
    (178, "Swallowed M80", 561, "Derrota a Mother con Tainted Samson",
     "Al recibir daño, explotas haciendo daño en área."),
    (179, "RC Remote", 580, "Derrota a Isaac, ???, Satan y The Lamb con Tainted Jacob",
     "Tu objeto activo se puede usar a distancia con un botón extra."),
    (180, "Found Soul", 581, "Derrota a Mother con Tainted Jacob",
     "Familiar fantasmal que dispara lágrimas con efecto."),
    (181, "Expansion Pack", 578, "Derrota a Isaac, ???, Satan y The Lamb con Tainted Bethany",
     "Tu activo gana un segundo uso al cargarse."),
    (182, "Beth's Essence", 579, "Derrota a Mother con Tainted Bethany",
     "Convierte tu segunda alma en otra Bethany al recoger Wisp."),
    (183, "The Twins", 570, "Derrota a Isaac, ???, Satan y The Lamb con Tainted Lilith",
     "Si tienes un familiar, hay probabilidad de duplicarlo cada sala."),
    (184, "Adoption Papers", 571, "Derrota a Mother con Tainted Lilith",
     "Tus familiares hacen +50% más de daño."),
    (185, "Cricket Leg", 574, "Derrota a Isaac, ???, Satan y The Lamb con Tainted Apollyon",
     "↑ Daño +0.3, ↑ Lágrimas +0.7."),
    (186, "Apollyon's Best Friend", 575, "Derrota a Mother con Tainted Apollyon",
     "Si tienes Void, los items absorbidos sueltan un Locust friend."),
    (187, "Broken Glasses", 521, "Completa Seeing Double (reto #40)",
     "Tus lágrimas tienen probabilidad de duplicarse y rebotar."),
    (188, "Ice Cube", 522, "Completa Pica Run (reto #41)",
     "Tus lágrimas tienen probabilidad de congelar a los enemigos."),
    (189, "Sigil of Baphomet", 518, "Completa Bloody Mary (reto #37)",
     "Al limpiar una sala, 5% de probabilidad de spawnear Black Heart o item demoníaco."),
]


def main() -> None:
    out_path = ROOT / "tracker" / "assets" / "trinkets_inline.js"
    lines = ["window.TRINKETS_DATA = ["]
    for tid, name, ach_id, unlock, desc in TRINKETS:
        entry = {
            "id": tid,
            "name": name,
            "achId": ach_id,
            "unlock": unlock,
            "desc": desc,
        }
        lines.append("  " + json.dumps(entry, ensure_ascii=False, separators=(",", ":")) + ",")
    lines.append("];")
    out = "\n".join(lines) + "\n"
    out_path.write_text(out, encoding="utf-8")

    total = len(TRINKETS)
    with_ach = sum(1 for t in TRINKETS if t[2] is not None)
    initial = total - with_ach
    print(f"Wrote {out_path}")
    print(f"  Total: {total} trinkets")
    print(f"  Con achievement: {with_ach}")
    print(f"  Iniciales:        {initial}")


if __name__ == "__main__":
    main()
