"""Extract cards/runes metadata from a local Isaac install.

Usage:
    python tools/build_cards.py [resources_dir]

Reads:
    pocketitems.xml   - card/rune definitions (id, type, name/description keys)
    stringtable.sta   - i18n strings (English names for V1)

Writes:
    tracker/data/cards.py   - {id: {name, sprite, removed, desc_es, group, unlock}}

Sprites (card_NNN.png) are generated by a separate task and are referenced
here only by filename. desc_es is left empty for V1 (Spanish translation is
a V2 follow-up).

The `unlock` field is the English unlock-condition text for cards gated by
an achievement (looked up via the `achievement=` attribute on <card>/<rune>
elements against tracker/data/achievements.json). Cards unlocked from the
start carry an empty string.
"""
from __future__ import annotations

import json
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

# Project root on sys.path so `from tracker.data...` works when invoked as
# `python tools/build_cards.py` from the repo root.
_PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

# EID Spanish card descriptions (generated by tools/build_eid.py). Optional —
# if the file isn't generated yet, all desc_es fields remain empty strings.
try:
    from tracker.data.eid_cards import EID_CARDS  # type: ignore
except ImportError:
    EID_CARDS: dict[int, dict] = {}

DEFAULT_RESOURCES = Path(
    "C:/Program Files (x86)/Steam/steamapps/common/"
    "The Binding of Isaac Rebirth/extracted_resources/resources"
)

# Manual Spanish translations of unlock-condition strings. Keys MUST match the
# English `Unlock` text in tracker/data/achievements.json byte-for-byte. Any
# string not in this dict is emitted in English (logged as a warning).
# Proper names (challenges, bosses, characters, items) are kept in English to
# match the existing style of trinkets_inline.js ("Derrota a The Lamb con
# Judas").
UNLOCK_TRANSLATIONS_ES: dict[str, str] = {
    # Runes — challenge completions (#1..#12, plus the late-game Repentance ones)
    "Complete Pitch Black (challenge #1)": "Completa Pitch Black (reto #1)",
    "Complete High Brow (challenge #2)": "Completa High Brow (reto #2)",
    "Complete Head Trauma (challenge #3)": "Completa Head Trauma (reto #3)",
    "Complete Darkness Falls (challenge #4)": "Completa Darkness Falls (reto #4)",
    "Complete The Tank (challenge #5)": "Completa The Tank (reto #5)",
    "Complete Solar System (challenge #6)": "Completa Solar System (reto #6)",
    "Complete Suicide King (challenge #7)": "Completa Suicide King (reto #7)",
    "Complete Cat Got Your Tongue (challenge #8)": "Completa Cat Got Your Tongue (reto #8)",
    "Complete Demo Man (challenge #9)": "Completa Demo Man (reto #9)",
    "Complete Cursed (challenge #10)": "Completa Cursed (reto #10)",
    "Complete Glass Cannon (challenge #11)": "Completa Glass Cannon (reto #11)",
    "Complete When Life Gives You Lemons (challenge #12)": "Completa When Life Gives You Lemons (reto #12)",
    "Complete Purist (challenge #20)": "Completa Purist (reto #20)",
    "Complete SPEED! (challenge #22)": "Completa SPEED! (reto #22)",
    "Complete The Guardian (challenge #30)": "Completa The Guardian (reto #30)",
    "Complete Hot Potato (challenge #42)": "Completa Hot Potato (reto #42)",
    "Complete Cantripped (challenge #43)": "Completa Cantripped (reto #43)",
    "Complete Red Redemption (challenge #44)": "Completa Red Redemption (reto #44)",
    "Complete DELETE THIS (challenge #45)": "Completa DELETE THIS (reto #45)",
    # Aces of clubs/diamonds/spades/hearts
    "Get a 3-win streak": "Consigue una racha de 3 victorias",
    "Defeat The Lamb in under 20 minutes": "Derrota a The Lamb en menos de 20 minutos",
    "Defeat The Lamb without taking hearts, coins, and bombs through an entire run":
        "Derrota a The Lamb sin recoger corazones, monedas ni bombas en toda la run",
    "Complete a Chapter (floors I and II) after The Basement, start-to-finish, with only half a heart of health (can use The Lost)":
        "Completa un Chapter (pisos I y II) después de The Basement, de principio a fin, con solo medio corazón de salud (puedes usar The Lost)",
    # Special cards from Repentance era
    "Have both the Broken Watch and the Stop Watch in your collection":
        "Ten Broken Watch y Stop Watch a la vez en tu colección",
    "Increase in size 5 times in a single run. Sources of increased size include \"One Makes you Larger\" pills, XI - Strength, and Magic Mushroom":
        "Aumenta de tamaño 5 veces en una sola run. Fuentes: píldoras \"One Makes you Larger\", XI - Strength y Magic Mushroom",
    "Open the large version of Mom's Box in Home": "Abre la versión grande de Mom's Box en Home",
    "Use cards and runes 20 times": "Usa cartas y runas 20 veces en total",
    "Defeat Delirium as The Lost": "Derrota a Delirium con The Lost",
    # Ultra Greedier — Apollyon variant (non-tainted)
    "Defeat Ultra Greedier as Apollyon": "Derrota a Ultra Greedier con Apollyon",
    # Mega Satan tainted variants
    "Defeat Mega Satan as Tainted Eden": "Derrota a Mega Satan con Tainted Eden",
    "Defeat Mega Satan as Tainted Magdalene": "Derrota a Mega Satan con Tainted Magdalene",
    # Soul cards — defeat Hush + Boss Rush with each tainted character
    "Defeat Hush and Boss Rush as Tainted Isaac": "Derrota a Hush y al Boss Rush con Tainted Isaac",
    "Defeat Hush and Boss Rush as Tainted Magdalene": "Derrota a Hush y al Boss Rush con Tainted Magdalene",
    "Defeat Hush and Boss Rush as Tainted Cain": "Derrota a Hush y al Boss Rush con Tainted Cain",
    "Defeat Hush and Boss Rush as Tainted Judas": "Derrota a Hush y al Boss Rush con Tainted Judas",
    "Defeat Hush and Boss Rush as Tainted ???": "Derrota a Hush y al Boss Rush con Tainted ???",
    "Defeat Hush and Boss Rush as Tainted Eve": "Derrota a Hush y al Boss Rush con Tainted Eve",
    "Defeat Hush and Boss Rush as Tainted Samson": "Derrota a Hush y al Boss Rush con Tainted Samson",
    "Defeat Hush and Boss Rush as Tainted Azazel": "Derrota a Hush y al Boss Rush con Tainted Azazel",
    "Defeat Hush and Boss Rush as Tainted Lazarus": "Derrota a Hush y al Boss Rush con Tainted Lazarus",
    "Defeat Hush and Boss Rush as Tainted Eden": "Derrota a Hush y al Boss Rush con Tainted Eden",
    "Defeat Hush and Boss Rush as Tainted Lost": "Derrota a Hush y al Boss Rush con Tainted Lost",
    "Defeat Hush and Boss Rush as Tainted Lilith": "Derrota a Hush y al Boss Rush con Tainted Lilith",
    "Defeat Hush and Boss Rush as Tainted Keeper": "Derrota a Hush y al Boss Rush con Tainted Keeper",
    "Defeat Hush and Boss Rush as Tainted Apollyon": "Derrota a Hush y al Boss Rush con Tainted Apollyon",
    "Defeat Hush and Boss Rush as Tainted Forgotten": "Derrota a Hush y al Boss Rush con Tainted Forgotten",
    "Defeat Hush and Boss Rush as Tainted Bethany": "Derrota a Hush y al Boss Rush con Tainted Bethany",
    "Defeat Hush and Boss Rush as Tainted Jacob": "Derrota a Hush y al Boss Rush con Tainted Jacob",
    # Reverse Tarot cards — defeat Ultra Greedier with each tainted character
    "Defeat Ultra Greedier as Tainted Isaac": "Derrota a Ultra Greedier con Tainted Isaac",
    "Defeat Ultra Greedier as Tainted Magdalene": "Derrota a Ultra Greedier con Tainted Magdalene",
    "Defeat Ultra Greedier as Tainted Cain": "Derrota a Ultra Greedier con Tainted Cain",
    "Defeat Ultra Greedier as Tainted Judas": "Derrota a Ultra Greedier con Tainted Judas",
    "Defeat Ultra Greedier as Tainted ???": "Derrota a Ultra Greedier con Tainted ???",
    "Defeat Ultra Greedier as Tainted Eve": "Derrota a Ultra Greedier con Tainted Eve",
    "Defeat Ultra Greedier as Tainted Samson": "Derrota a Ultra Greedier con Tainted Samson",
    "Defeat Ultra Greedier as Tainted Azazel": "Derrota a Ultra Greedier con Tainted Azazel",
    "Defeat Ultra Greedier as Tainted Lazarus": "Derrota a Ultra Greedier con Tainted Lazarus",
    "Defeat Ultra Greedier as Tainted Eden": "Derrota a Ultra Greedier con Tainted Eden",
    "Defeat Ultra Greedier as Tainted Lost": "Derrota a Ultra Greedier con Tainted Lost",
    "Defeat Ultra Greedier as Tainted Lilith": "Derrota a Ultra Greedier con Tainted Lilith",
    "Defeat Ultra Greedier as Tainted Keeper": "Derrota a Ultra Greedier con Tainted Keeper",
    "Defeat Ultra Greedier as Tainted Apollyon": "Derrota a Ultra Greedier con Tainted Apollyon",
    "Defeat Ultra Greedier as Tainted Forgotten": "Derrota a Ultra Greedier con Tainted Forgotten",
    "Defeat Ultra Greedier as Tainted Bethany": "Derrota a Ultra Greedier con Tainted Bethany",
    "Defeat Ultra Greedier as Tainted Jacob": "Derrota a Ultra Greedier con Tainted Jacob",
}

# stringtable.sta: <key> has 8 <string> children, one per language, in this order
# (confirmed against pocketitems.xml's <languages> block — Key lang at index 0
# does not get its own <string> child, the first <string> is English).
_LANG_ORDER = ["en", "jp", "kr", "zh", "ru", "de", "es", "fr"]
_LANG_INDEX = {lang: i for i, lang in enumerate(_LANG_ORDER)}


def _strip_key(attr_value: str) -> str:
    """`#THE_FOOL_NAME` -> `THE_FOOL_NAME`."""
    return (attr_value or "").lstrip("#")


def parse_stringtable(stringtable_xml: Path) -> dict[str, dict[str, str]]:
    """Return {key_name: {lang_code: translated_string}}."""
    root = ET.parse(stringtable_xml).getroot()
    out: dict[str, dict[str, str]] = {}
    for key_elem in root.iter("key"):
        name = key_elem.get("name")
        if not name:
            continue
        strings = [s.text or "" for s in key_elem.findall("string")]
        translations: dict[str, str] = {}
        for lang, i in _LANG_INDEX.items():
            if i < len(strings) and strings[i]:
                translations[lang] = strings[i]
        out[name] = translations
    return out


def classify_group(elem_tag: str, type_attr: str, name_key: str) -> str:
    """Map a pocketitem element to one of the 5 logical groups.

    Rules (in priority order):
      1. name key starts with SOUL_OF_ -> 'objetos_alma'
         (the XML labels Soul stones type="rune", but they are conceptually
         a separate group in the tracker.)
      2. type contains 'reverse' (e.g. 'tarot_reverse') -> 'tarot_inverso'
      3. type == 'tarot' -> 'tarot_mayor'
      4. type == 'rune' OR elem tag == 'rune' -> 'runas'
      5. anything else (suit, special, object, ...) -> 'especiales'
    """
    t = (type_attr or "").lower()
    if name_key.startswith("SOUL_OF_"):
        return "objetos_alma"
    if "reverse" in t:
        return "tarot_inverso"
    if t == "tarot":
        return "tarot_mayor"
    if t == "rune" or elem_tag == "rune":
        return "runas"
    return "especiales"


def load_achievements_unlock(achievements_json: Path) -> dict[int, str]:
    """Return {achievement_id: unlock_text} parsed from achievements.json."""
    with achievements_json.open(encoding="utf-8") as fh:
        data = json.load(fh)
    out: dict[int, str] = {}
    for entry in data:
        try:
            aid = int(entry["Id"])
        except (KeyError, TypeError, ValueError):
            continue
        out[aid] = entry.get("Unlock") or ""
    return out


def parse_pocketitems(
    pocketitems_xml: Path,
    strings: dict[str, dict[str, str]],
    ach_unlock: dict[int, str],
) -> tuple[list[dict], list[str]]:
    """Return ([{id, name, removed, desc_es, group, unlock}, ...], warnings)."""
    root = ET.parse(pocketitems_xml).getroot()
    out: list[dict] = []
    warnings: list[str] = []

    # Track every distinct (tag, type) combination we saw, for the warning log.
    seen_type_combos: set[tuple[str, str]] = set()

    for elem in root:
        if elem.tag not in ("card", "rune"):
            # pilleffect (and any future tag) — not our concern here.
            continue
        id_attr = elem.get("id")
        if id_attr is None:
            continue
        try:
            card_id = int(id_attr)
        except ValueError:
            warnings.append(f"non-integer id={id_attr!r} — skipped")
            continue

        name_attr = elem.get("name") or ""
        # id=0 has name="NULL" — the canonical "no card" sentinel.
        if card_id == 0 or name_attr.upper() == "NULL":
            out.append({
                "id": card_id,
                "name": "",
                "removed": True,
                "desc_es": "",
                "group": "",
                "unlock": "",
            })
            continue

        name_key = _strip_key(name_attr)
        type_attr = elem.get("type") or ""
        seen_type_combos.add((elem.tag, type_attr.lower()))

        # English name from stringtable (V1 spec).
        name_en = strings.get(name_key, {}).get("en", "")
        if not name_en:
            warnings.append(
                f"id={card_id} key={name_key!r} has no English string — "
                f"using key as fallback"
            )
            # Last-resort fallback: humanize the key.
            base = name_key[:-5] if name_key.endswith("_NAME") else name_key
            name_en = " ".join(p.capitalize() for p in base.split("_"))

        group = classify_group(elem.tag, type_attr, name_key)
        # Spanish description from EID (if available — empty string otherwise).
        desc_es = EID_CARDS.get(card_id, {}).get("desc", "")
        # Unlock condition (English) — only present if the XML element has an
        # `achievement` attribute AND that id exists in achievements.json.
        ach_attr = elem.get("achievement")
        unlock = ""
        if ach_attr is not None:
            try:
                ach_id = int(ach_attr)
            except ValueError:
                warnings.append(
                    f"id={card_id} has non-integer achievement={ach_attr!r}"
                )
            else:
                if ach_id in ach_unlock:
                    english = ach_unlock[ach_id]
                    if english in UNLOCK_TRANSLATIONS_ES:
                        unlock = UNLOCK_TRANSLATIONS_ES[english]
                    else:
                        unlock = english
                        warnings.append(
                            f"id={card_id} unlock has no Spanish translation: "
                            f"{english!r}"
                        )
                else:
                    warnings.append(
                        f"id={card_id} references unknown achievement id "
                        f"{ach_id} — unlock left empty"
                    )
        out.append({
            "id": card_id,
            "name": name_en,
            "removed": False,
            "desc_es": desc_es,
            "group": group,
            "unlock": unlock,
        })

    # Warn (informational) about every type we saw, so future runs can
    # spot newly-introduced types we may need to map explicitly.
    known = {
        ("card", "tarot"), ("card", "suit"), ("card", "special"),
        ("card", "object"), ("card", "tarot_reverse"), ("card", "rune"),
        ("rune", "rune"),
    }
    for combo in sorted(seen_type_combos):
        if combo not in known:
            warnings.append(f"unknown (tag,type) combination: {combo}")

    out.sort(key=lambda d: d["id"])
    return out, warnings


def fill_id_gaps_as_removed(cards: list[dict]) -> list[dict]:
    """Mirror collectibles.py: if a numeric id is missing, insert a removed
    placeholder so consumers can iterate by id without holes."""
    by_id = {c["id"]: c for c in cards}
    if not by_id:
        return cards
    max_id = max(by_id)
    out = []
    for i in range(0, max_id + 1):
        if i in by_id:
            out.append(by_id[i])
        else:
            out.append({
                "id": i, "name": "", "removed": True,
                "desc_es": "", "group": "", "unlock": "",
            })
    return out


def write_cards_py(cards: list[dict], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        '"""Auto-generated by tools/build_cards.py — do not edit by hand."""',
        "from __future__ import annotations",
        "",
        "# id -> {name (English V1), sprite, removed, desc_es, group, unlock}",
        "# Sprite filenames live under tracker/assets/card_icons/ (generated separately).",
        '# Group ∈ {"tarot_mayor", "tarot_inverso", "runas", "especiales", "objetos_alma"}.',
        "# `unlock` is the Spanish unlock-condition text (translated from",
        "# achievements.json) for cards gated by an achievement. Empty string",
        "# means unlocked by default. Any missing translation falls back to English.",
        "CARDS: dict[int, dict] = {",
    ]
    for c in cards:
        sprite = f"card_{c['id']:03d}.png" if not c["removed"] else ""
        lines.append(
            f"    {c['id']}: {{"
            f"'name': {c['name']!r}, "
            f"'sprite': {sprite!r}, "
            f"'removed': {c['removed']}, "
            f"'desc_es': {c['desc_es']!r}, "
            f"'group': {c['group']!r}, "
            f"'unlock': {c['unlock']!r}"
            f"}},"
        )
    lines.append("}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main(argv: list[str]) -> int:
    resources_dir = Path(argv[1]) if len(argv) > 1 else DEFAULT_RESOURCES
    if not resources_dir.is_dir():
        print(f"[build_cards] resources dir not found: {resources_dir}", file=sys.stderr)
        return 1

    pocketitems_path = resources_dir / "pocketitems.xml"
    stringtable_path = resources_dir / "stringtable.sta"
    for p in (pocketitems_path, stringtable_path):
        if not p.exists():
            print(f"[build_cards] missing input: {p}", file=sys.stderr)
            return 1

    print(f"[build_cards] resources: {resources_dir}")
    strings = parse_stringtable(stringtable_path)
    print(f"[build_cards] {len(strings)} stringtable keys")

    project_root = Path(__file__).resolve().parents[1]
    ach_path = project_root / "tracker" / "data" / "achievements.json"
    if ach_path.exists():
        ach_unlock = load_achievements_unlock(ach_path)
        print(f"[build_cards] {len(ach_unlock)} achievement unlock entries loaded")
    else:
        ach_unlock = {}
        print(f"[build_cards][warn] {ach_path} not found — unlock fields will be empty")

    cards_raw, warnings = parse_pocketitems(pocketitems_path, strings, ach_unlock)
    cards = fill_id_gaps_as_removed(cards_raw)

    for w in warnings:
        print(f"[build_cards][warn] {w}")

    out_py = project_root / "tracker" / "data" / "cards.py"
    write_cards_py(cards, out_py)

    real = sum(1 for c in cards if not c["removed"])
    with_desc = sum(1 for c in cards if not c["removed"] and c["desc_es"])
    with_unlock = sum(1 for c in cards if not c["removed"] and c["unlock"])
    print(f"[build_cards] wrote {len(cards)} cards ({real} real, "
          f"{len(cards) - real} removed/placeholder) -> {out_py}")
    print(f"[build_cards] EID Spanish descriptions: {with_desc}/{real} cards covered")
    print(f"[build_cards] Unlock conditions: {with_unlock}/{real} cards have one")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
